DROP DATABASE blog_db;
CREATE DATABASE blog_db;
USE blog_db;

CREATE TABLE articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifDate DATETIME NULL
);

CREATE TABLE comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ArticleId INT NOT NULL,
    author VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ArticleId) REFERENCES articles(id) ON DELETE CASCADE
);
